name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test blake3-hash-wasm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "16"
      - run: |
          npm i
          npm t
